apiVersion: v1
kind: Deployment
metadata:
  name: gateway-deploy
  labels:
    app: gateway-deploy
    type: microservice
spec:
  replicas: 1
  selector: 
    matchlabel:
      app: gateway
      type: microservice
  template: 
    metadata:
      name: gateway-pod
      labels:
        app: gateway
        type: microservice
    spec:
       containers:
        - name : gateway-app
          image: jpferreyradev/serviciosapigateway:latest
          ports:
            - containerPort:80