apiVersion: v1
kind: Deployment
metadata:
  name: microservice-libreria-deploy
  labels:
    app: microservice-libreria-deploy
    type: microservice
spec:
  replicas: 2
  selector: 
    matchlabel:
      app: microservice-libreria
      type: microservice
  template: 
    metadata:
      name: microservice-libreria-pod
      labels:
        app: microservice-libreria
        type: microservice
    spec:
      containers:
        - name : microservice-libreria-app
          image: jpferreyradev/serviciosapilibreria:latest
          ports:
            - containerPort:80
          env:
            - name: MongoDb__ConnectionString
              value: Mongodb://vaxidrez:$VaxiDrez2025@mongo-service:27027