apiVersion: v1
kind: Deployment
metadata:
  name: mongo-service
  labels:
    name: mongo-service
    app: database
  spec:
    type: LoadBalancer
    ports:
      - port: 27017
        targetPort: 27017
    selector:
      app: microservice-libreria
      name: mongo-pod