apiVersion: v1
kind: Deployment
metadata:
  name: mongo-deploy
  labels:
    app: mongo-deploy
    type: microservice-libreria
spec:
    replicas: 1
    selector: 
      matchlabel:
        app: microservice-libreria
        name: mongo-pod
      template:
        metadata:
          name: mongo-pod
          labels:
            app: microservice-libreria
            name: mongo-pod
        spec:
          containers:
            - name : mongo
              image: mongo:4.2.12
              command:
              - /bin/bash
              - -c
              env:
              - name: MONGO_INITDB_ROOT_USERNAME
                value: "vaxidrez"
              -name: MONGO_INITDB_ROOT_PASSWORD
                value "$VaxiDrez2025"
              ports:
                - containerPort: 27017