apiVersion: v1
kind: Deployment
metadata:
  name: mssql-service
  labels:
    name: mssql-service
    app: database
  spec:
    type: LoadBalancer
    ports:
      - port: 27017
        targetPort: 27017
    selector:
      app: microservice-seguridad
      name: mssql-pod