apiVersion: v1
kind: Pod
metadata:
  name: mssql
  labels:
    app: microservice-seguridad
    name: mssql-pod
spec:
  containers:
    - name : mssql
      image: docker pull mcr.microsoft.com/mssql/server      
      env:
      - name: ACCEPT_EULA
        value: "Y"
      -name: SA_PASSWORD
        value "$VaxiDrez2025"